### ISSUE TITLE
how to implement onclick webview l.loadUrl on this..its crashing..thanx

### ISSUE THREAD

**Issue by smoochiee** [mufasa08/HorizontalViewPagerWebView#1]
help

**Comment by mufasa08** [comment]
Please clarify the question.

**Comment by smoochiee** [comment]
@mufasa08 i want to add button with different url..like clicking button will load url in a viewpager..

**Comment by smoochiee** [comment]
i want to change this switch (sectionNumber) {

case 1:

url="https://www.google.com/search?q=news";

break;

case 2:

url="https://www.google.com/search?q=random";

break;

case 3:

url="https://www.amazon.com/Hoover-UH20040-QuickVac-Bagless-Upright/dp/B004N64GH0/ref=br_dig_pdt-1?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=&pf_rd_r=0MZDRMZPKF0R2NT18GQ1&pf_rd_t=36701&pf_rd_p=abc0a418-efdb-4eb8-923e-3437111895cf&pf_rd_i=desktop";

break;

}

on button click..

**Comment by smoochiee** [comment]
im planning to add a nav drawer with different urls..my question is how to pass my nav drawer urls to viewpager webview

**Comment by mufasa08** [comment]
Change Placeholder Fragment newInstance code and pass your url on fragment creation from activity.

 public static PlaceholderFragment newInstance(int sectionNumber) {
            PlaceholderFragment fragment = new PlaceholderFragment();
            Bundle args = new Bundle();
            args.putInt(ARG_SECTION_NUMBER, sectionNumber);
            args.putString(ARG_URL, url);
            fragment.setArguments(args);
            return fragment;

**Comment by smoochiee** [comment]
thanks..ill try this..:blush:

**Comment by mufasa08** [comment]
No problem.

**Comment by smoochiee** [comment]
i solve this way 


  WebSettings settings=webView.getSettings();
            webView.setWebChromeClient(new WebChromeClient());
            webView.setWebViewClient(new WebViewClient());
            settings.setJavaScriptEnabled(true);
            webView.setScrollContainer(false);
            webView.setVerticalScrollBarEnabled(false);
            webView.setHorizontalScrollBarEnabled(false);
            settings.setBuiltInZoomControls(true);
            settings.setSupportZoom(true);
            settings.setDisplayZoomControls(false);
            settings.setLoadWithOverviewMode(true);
            settings.setUseWideViewPort(true);
            webView.loadUrl(url);



            mbutton.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    webView.loadUrl("http://google.com");
                }
            });
            return rootView;
        }

**Comment by mufasa08** [comment]
Nice good job. Glad it works for you.
